name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
defaults:
  run:
    shell: bash
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  upload:
    needs: create
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        include:
          - os: windows
            suffix: .exe
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: amd64
      GOEXE: ${{ matrix.suffix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - run: |
          echo "asset_path=depster$(go env GOEXE)" >> $GITHUB_ENV
          echo "asset_name=$(go env GOOS)-$(go env GOARCH)-depster$(go env GOEXE)" >> $GITHUB_ENV
      - run: make ${{ env.asset_path }}
      - run: |
          sudo apt-get install -y gnupg
          base64 -d <(printf "${{ secrets.signing_key }}") | gpg --import
          gpg --detach-sign --armor ${{ env.asset_path }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ${{ env.asset_path }}
          asset_name: ${{ env.asset_name }}
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ${{ env.asset_path }}.asc
          asset_name: ${{ env.asset_name }}.asc
          asset_content_type: application/pgp-signature
