name: unit
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make unit
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.out
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage
      - run: sed -i'' "s:^github.com/$GITHUB_REPOSITORY/::" coverage.out
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.out
          fail_ci_if_error: true
